apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: <ECR_REPO_URL_WORKER>:latest
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:3002"
